### ISSUE TITLE
What is going here

### ISSUE THREAD

**Issue by jewel109** [Muhammet-Yildiz/Mern-Blog#1]
https://github.com/Muhammet-Yildiz/Mern-Blog/blob/226f8f15461961ea0a1f5aeb0435bdb62b61cdfc/Backend/Models/story.js#L66-L74

why did you write this hook and why you don't need to call the next()

**Comment by Muhammet-Yildiz** [comment]
If a story is deleted, all comments must be deleted before the next()
operation is done, because there is nothing to be done after this is
deleted.


Raihanur Rahman ***@***.***>, 30 Haz 2022 Per, 09:44
tarihinde şunu yazdı:
